apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: hw2
  labels:
    app: my-app
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - name: http
      protocol: TCP
      port: 9191
      targetPort: web
